### ISSUE TITLE
Map Range Renders Incorrectly

### ISSUE THREAD

**Issue by Cantersoft** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#468]
**System Setup: AMD RX570, Intel Core i7, Windows 10, Blender 3.0.1**

After conducting multiple experiments, I have determined that Radeon ProRender is incapable of rendering gradients created using Map Range. See the following example:

**Cycles**
<img width="600" alt="Cycles- trial3" src="https://user-images.githubusercontent.com/46493366/159076497-bf1f18c4-d7cc-4ef9-bc65-c9bf48d4fc28.png">

**Radeon ProRender**
<img width="600" alt="Radeon ProRender- trial3" src="https://user-images.githubusercontent.com/46493366/159076483-5f2ea126-90ea-4de0-a04b-6f2c59f17561.png">

***.blend file:** [cube.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/8307390/cube.zip)

**Comment by bsavery** [comment]
I don't think we added support for this node.  Is it new?

**Comment by Cantersoft** [comment]
I believe the node has existed since version 2.92. Could you please add support for this node? I need it for a practical project.

**Comment by lenhone** [comment]
Map Range appears in the [2.81 manual](https://docs.blender.org/manual/en/2.81/render/shader_nodes/converter/map_range.html) so late 2019.

According to [RadeonProRenderDocs](https://radeon-pro.github.io/RadeonProRenderDocs/en/plugins/blender/shader_nodes.html) because "map range" doesn't appear in the add menu when RadeonProRenderBlenderAddon is selected it is not supported. However this isn't a great way to convey support as the nodes can still be added by selecting EEVEE or Cycles or opening an existing project. 

There is an error in console but most probably don't see it.
`Ignoring unsupported node <bpy_struct, ShaderNodeMapRange("Map Range") at 0x7faa37731a08, evaluated> <bpy_struct, Material("Material") at 0x7faa37726d08, evaluated>`

I think this question relates to discussion #435, essentially is there any plan to support all nodes?

**Comment by Cantersoft** [comment]
> Is there any plan to support all nodes?

I hope so, cause otherwise I'm gonna have to render everything with CPU.

Anyway, I'm just going to put this information here: I don't understand how renderers work, but I have sufficient programming knowledge. I wouldn't mind learning to attempt to contribute to ProRender and get it fully-featured if the devs need help.

**Comment by bsavery** [comment]
Supporting every node would probably be impossible.  But this one should be easier.

**Comment by bsavery** [comment]
Hi There.  

Since you're hoping to help contribute, let me give a simple walkthrough of how I'd approach this Node!  

Map range is really doing exactly what it's saying... remapping a range of values from one to another.  One good example is many texture values are 0-1, but maybe you want them ranging from -1 to 1 for displacement.  

https://docs.blender.org/manual/en/latest/render/shader_nodes/converter/map_range.html


In this case you would do something like:
```
from_range = from_max - from_min
to_range = to_max - to_min
if clamp:
    value = clamp_value(value, from_min, from_max)
point_in_from_range = value - from_min
result = from_min + point_in_from_range * (to_range / from_range)
``` 
This of course is just the linear case.  

To add this function to RPR you need to do two things: 
1.  Add the Map Range node class to https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/blob/5e0c4ee69a439641a0d5dad094fe111eed3e98fa/src/rprblender/nodes/__init__.py#L39

2.  Add a class in https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/blob/master/src/rprblender/nodes/blender_nodes.py (with the name of the node class ShaderNodeMapRange

You can basically just use python here to do your math.  What is happening behind the scenes is that the input values are getting turned into RPR "gpu shader nodes" and the math is compiled and executed when the shader runs.  



I made an example of how to do this here.  See the code for an example and expand upon to do more than just 'linear'. I appreciate the help!
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/pull/471

**Comment by bsavery** [comment]
Let me know if you have questions

**Comment by ARozghon** [comment]
Map Range node now supported with RPR 3.3.29 built and later, please, wait for release one of this builds and check if it was fixed in you case. Thank you
