### ISSUE TITLE
The add on won't load.  I just bought a 12core 24thread cpu, a 5700xt GPU to do 3d rendering and graphics work and I literally can barely run blender and doing rendering is a all day process..  I literally spent all the money I had.  This is messed up that AMD throws up a github and just basically says figure it out.. and it still doesn't work.  Never buying AMD again.  I spent every dollar I had so I could do work in graphics.  What a mistake trusting AMD

### ISSUE THREAD

**Issue by negaunee042** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#474]
Every issue should include 3 things:
1.  System setup (GPU, CPU, OS version, Blender version)
2.  **Most ideally** a .blend scene to reproduce this simply.  **SCREENSHOTS OR RENDERS ARE NOT A SCENE FILE**
3.  What the expected behavior or effect is.  If possible include the error message.  

You can get more information on the error message by opening Window -> Show System Console from blender and copying that text here.  On MacOS launch Blender from the Terminal.

**Comment by negaunee042** [comment]
This is my errors.. What a joke
![image](https://user-images.githubusercontent.com/97860719/160272399-5b06f1e2-cedc-405e-9c98-dd74f2dd59ab.png)

**Comment by wilderWiesel** [comment]
First I suggest you to fill in the form properly, otherwise nobody will be able to help you. 

I asked my crystal ball and  the guessing is, you use a none compatible Blender version. If this the case you are not alone, it is already  mentioned in former issue reports. Solutions included. 

Have a nice Sunday. 
enjoy the free content

**Comment by bsavery** [comment]
Every issue should include 3 things:

System setup (GPU, CPU, OS version, Blender version)
Most ideally a .blend scene to reproduce this simply. SCREENSHOTS OR RENDERS ARE NOT A SCENE FILE
What the expected behavior or effect is. If possible include the error message.
You can get more information on the error message by opening Window -> Show System Console from blender and copying that text here. On MacOS launch Blender from the Terminal.


What version of blender are you using?  If it's blender 3.1 there is another issue https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/467 covering why that doesn't work, and we have a pending change to help fix that: https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/pull/454

No one is saying "figure it out yourself" but if you can't make a proper bug report we can't help you.

**Comment by ericwomer** [comment]
The error is Blenders fault, not AMDs as the Blender foundation switched up dependency version of libs and python last minuet and didn't give addon developers time to update things on their end.

**Comment by negaunee042** [comment]
You're right.  I was butthurt at AMD, not anyone else.  Wasn't trying to go on a rant about the devs to this.  I'm sorry.  I'd imagine with ETH mining dying soon, a lot of the AMD GPU's will be crossed over to gaming or working desktops so I'd imagine a lot of confused people with issues in 5-6 month range.
