### ISSUE TITLE
shading pannel on blender showing black screen help 

### ISSUE THREAD

**Issue by xalteropsx** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#492]
https://drive.google.com/file/d/1Np7jkO6kKkBAAnhrmwqCer5kLwZcLJkG/view?usp=sharing

what is this bug? why it show black screen

**Comment by bsavery** [comment]
We need more info.  Not just a screen shot.

**Comment by xalteropsx** [comment]
what else i can give ?

**Comment by bsavery** [comment]
Hello. When you open an issue, there is a list of information suggested.


Every issue should include 3 things:
1.  System setup (GPU, CPU, OS version, Blender version)
2.  **Most ideally** a .blend scene to reproduce this simply.  **SCREENSHOTS OR RENDERS ARE NOT A SCENE FILE**
3.  What the expected behavior or effect is.  If possible include the error message.  

You can get more information on the error message by opening Window -> Show System Console from blender and copying that text here.  On MacOS launch Blender from the Terminal.




## Issue


## Steps to Reproduce



## System Setup (Environment)





## Detailed Description

**Comment by xalteropsx** [comment]
https://drive.google.com/drive/folders/1VEXIRJHuPubTZFtCb2IGJQkwo_gJXpdY?usp=sharing

**Comment by xalteropsx** [comment]
//variables list
rpr_context context_0x0000026D15B665C0 = NULL;
rpr_material_system materialsystem_0x0000026D8D767380 = NULL;
rpr_scene scene_0x0000026D8D764AE0 = NULL;
rpr_framebuffer framebuffer_0x0000026D8D766D40 = NULL;
rpr_framebuffer framebuffer_0x0000026D8D766C00 = NULL;
rpr_framebuffer framebuffer_0x0000026D8D764680 = NULL;
rpr_framebuffer framebuffer_0x0000026D8D765440 = NULL;
rpr_context context_0x0000026D15B65580 = NULL;
rpr_material_system materialsystem_0x0000026D064E96C0 = NULL;
rpr_scene scene_0x0000026D064E9300 = NULL;
rpr_framebuffer framebuffer_0x0000026D064E87C0 = NULL;
rpr_framebuffer framebuffer_0x0000026D064E9080 = NULL;
rpr_framebuffer framebuffer_0x0000026D064EA7A0 = NULL;
rpr_framebuffer framebuffer_0x0000026D064E9440 = NULL;

**Comment by bsavery** [comment]
Which version of the blender plugin did you use?

**Comment by xalteropsx** [comment]
3.3.29

**Comment by xalteropsx** [comment]
@bsavery  it already seems solve @[radeonprorender](https://github.com/radeonprorender) radeonprorender
[ v3.3.30](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/tree/v3.3.30)
 fa9b4a3 
Weekly Development builds v3.3.30 (04/22/2022) Pre-release
RPRBLND-2130: Error with "Material Preview" Viewport Shading mode (#482)



PURPOSE

Error with "Material Preview" Viewport Shading mode.
Ignoring changes in Viewport Shading panel while viewport render.

EFFECT OF CHANGE

Fixed error while using "Material Preview" Viewport Shading mode.
Fixed ignoring changes in Viewport Shading panel while viewport render.





 i downloaded new version 3.3.30 it fixed thnx
